spring:
  application:
    name: crm-auth-service

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/${POSTGRES_DB:authservice_dev}
    username: ${POSTGRES_USER:dev_user}
    password: ${POSTGRES_PASSWORD:dev_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        filter:
          enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

jwt:
  secret: ${JWT_SECRET:changeMeInProduction}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

app:
  super-admin:
    email: ${SUPER_ADMIN_EMAIL:admin@crm.com}
    password: ${SUPER_ADMIN_PASSWORD:SuperAdmin123!}
    first-name: ${SUPER_ADMIN_FIRSTNAME:Super}
    last-name: ${SUPER_ADMIN_LASTNAME:Admin}

  flyway:
    clean-on-startup: ${FLYWAY_CLEAN_ON_STARTUP:false}

logging:
  level:
    root: INFO
    com.crm.AuthService: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
