spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authservice_dev
    username: dev_user
    password: dev_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: devSecretKeyForLocalDevelopmentOnlyDoNotUseInProduction123456789
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
app:
  super-admin:
    email: admin@crm.com
    password: SuperAdmin123!
    first-name: Super
    last-name: Admin
  flyway:
    clean-on-startup: ${FLYWAY_CLEAN_ON_STARTUP:false}



logging:
  level:
    root: DEBUG
    com.crm.AuthService: TRACE
    org.flywaydb: TRACE
    org.springframework.security: DEBUG



