

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authservice_test
    username: test_user
    password: test_pass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: testSecretKeyForUnitTestsOnly
  expiration: 60000
  refresh-expiration: 120000

app:
  super-admin:
    email: test@admin.com
    password: TestPassword123!
    first-name: Test
    last-name: Admin

logging:
  level:
    root: WARN
    com.crm.AuthService: DEBUG